server:
  port: 8877
  shutdown: "graceful"
management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

springdoc:
  packagesToScan: uk.gov.hmcts.reform.mock.controllers
  writer-with-order-by-keys: true

spring:
  config:
    import: "optional:configtree:/mnt/secrets/send-letter/"
  application:
    name: Send Letter Mock

send-letter:
  url: ${SEND_LETTER_URL:http://localhost:1234}

idam:
  s2s-auth:
    url: ${AUTH_PROVIDER_SERVICE_CLIENT_BASEURL:http://localhost:1256}
    microservice: ${IDAM_S2S_AUTH_MICROSERVICE:sendletter}
    secret: ${IDAM_S2S_AUTH_TOTP_SECRET:verysecret}
